name: Preview

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches:
      - "main"

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Installing packages
        run: npm ci

      - name: Build Preview
        run: npm run build:preview

      - name: Deploy Preview
        run: npm run deploy
