name: Preview

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches:
      - "main"

jobs:
  preview:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Preview
        run: npm run build:preview

      - name: Deploy Preview
        run: npm run deploy
